
server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  data:
    mongodb:
#      uri: mongodb://localhost:27017/fb_project
      uri: mongodb://mongo:27017/fb_project
      database: fb_project

